import { spawn } from 'node:child_process'
import { chromium } from 'playwright'

const port = 4178
const origin = `http://127.0.0.1:${port}`
const server = spawn(process.execPath, ['node_modules/vite/bin/vite.js', '--host', '127.0.0.1', '--port', String(port)], { stdio:['ignore','pipe','pipe'] })
let browser

function assert(condition, message) { if (!condition) throw new Error(message) }
async function waitForServer() {
  for (let attempt=0; attempt<60; attempt+=1) {
    try { if ((await fetch(origin)).ok) return } catch { /* still starting */ }
    await new Promise((resolve)=>setTimeout(resolve,200))
  }
  throw new Error('Platform test server did not start')
}

try {
  await waitForServer()
  browser = await chromium.launch({ channel:'chrome', headless:true })
  const context = await browser.newContext()
  await context.addInitScript(() => { if (!localStorage.getItem('nt_state_v1')) localStorage.setItem('nt_state_v1', JSON.stringify({ onboardingComplete:true, selectedLanguage:'english', selectedLevel:'B1' })) })
  const page = await context.newPage()
  page.setDefaultTimeout(30000)
  const errors = []
  page.on('pageerror',(error)=>errors.push(error.message))
  page.on('console',(message)=>{ if (message.type()==='error') errors.push(message.text()) })

  await page.goto(`${origin}/vocabulary`)
  await page.getByRole('button',{ name:'Yêu thích' }).click()
  await page.getByRole('button',{ name:'Từ khó' }).click()
  await page.getByPlaceholder('Cách dùng, mẹo nhớ hoặc lỗi hay gặp…').fill('Dùng trong hội thoại công việc')
  await page.reload()
  assert(await page.getByRole('button',{ name:'Yêu thích' }).getAttribute('aria-pressed') === 'true', 'Favorite was not persisted')
  assert(await page.getByRole('button',{ name:'Từ khó' }).getAttribute('aria-pressed') === 'true', 'Difficult flag was not persisted')
  assert(await page.getByPlaceholder('Cách dùng, mẹo nhớ hoặc lỗi hay gặp…').inputValue() === 'Dùng trong hội thoại công việc', 'Vocabulary note was not persisted')
  await page.locator('.detailed-flashcard').click()
  await page.getByRole('button',{ name:/Nhớ/ }).click()
  await page.waitForFunction(() => Object.values(JSON.parse(localStorage.getItem('nt_state_v1')).flashcardProgress || {}).some((item)=>item.attempts===1 && item.nextReview))
  await page.getByRole('tab',{ name:'Quiz' }).click()
  await page.locator('.quiz-question .answer-list button').first().click()
  await page.getByRole('button',{ name:'Kiểm tra', exact:true }).click()
  await page.locator('.quiz-question .feedback').waitFor()
  await page.getByRole('tab',{ name:'Kho từ' }).click()
  await page.getByLabel('Ngôn ngữ').selectOption('chinese')
  assert(await page.locator('.vocabulary-index button').count() > 0, 'Chinese vocabulary is missing from library')
  await page.getByLabel('Level').selectOption('HSK 4')
  assert(await page.locator('.vocabulary-index button').count() >= 5, 'HSK 4 vocabulary set is missing')
  assert(!(await page.locator('.vocabulary-index').innerText()).includes('你好'), 'Starter words were incorrectly labelled HSK 4')
  await page.goto(`${origin}/vocabulary?language=chinese&level=HSK%201&word=%E4%BD%A0%E5%A5%BD`)
  await page.locator('.detailed-face.front h2').getByText('你好').waitFor()
  console.log('PLATFORM checkpoint: vocabulary SRS and quiz')

  await page.goto(`${origin}/toeic`)
  await page.getByRole('tab',{ name:'Listening Practice' }).click()
  await page.getByRole('progressbar',{ name:'Tiến độ audio' }).waitFor()
  await page.getByRole('tab',{ name:'Reading Practice' }).click()
  for (let question=0; question<15; question+=1) {
    await page.locator('.quiz-question .answer-list button').first().click()
    await page.getByRole('button',{ name:'Kiểm tra' }).click()
    if (question < 14) await page.getByRole('button',{ name:'Next' }).click()
    else await page.getByRole('button',{ name:'Xem kết quả' }).click()
  }
  await page.getByRole('heading',{ name:'Reading Practice hoàn thành' }).waitFor()
  await page.getByRole('tab',{ name:'Full Test' }).click()
  await page.getByRole('button',{ name:'Bắt đầu bài thi' }).click()
  assert(await page.locator('.full-question-nav .question-nav button').count() === 100,'TOEIC Listening must expose 100 questions')
  await page.locator('.full-question-nav .question-nav button').last().click()
  await page.locator('.quiz-question .answer-list button').first().click()
  await page.getByRole('button',{ name:/Nộp Listening · sang Reading/ }).click()
  assert(await page.locator('.full-question-nav .question-nav button').count() === 100,'TOEIC Reading must expose 100 questions')
  await page.locator('.full-question-nav .question-nav button').last().click()
  await page.locator('.quiz-question .answer-list button').first().click()
  await page.getByRole('button',{ name:'Nộp bài' }).click()
  await page.getByText('Estimated TOEIC Score').waitFor()
  assert((await page.evaluate(() => JSON.parse(localStorage.getItem('nt_state_v1')).toeicHistory?.length)) === 1, 'TOEIC full test result was not persisted')
  console.log('PLATFORM checkpoint: TOEIC 15-question practice completes and 200-question full test submits')

  await page.goto(`${origin}/ielts`)
  await page.getByRole('tab',{ name:'Reading Practice' }).click()
  for (let question=0; question<40; question+=1) {
    const choices=page.locator('.quiz-question .answer-list button')
    if (await choices.count()) await choices.first().click()
    else await page.locator('.quiz-question input').fill('practice answer')
    await page.getByRole('button',{ name:'Kiểm tra' }).click()
    if (question < 39) await page.getByRole('button',{ name:'Next' }).click()
    else await page.getByRole('button',{ name:'Xem kết quả' }).click()
  }
  await page.getByRole('heading',{ name:'IELTS Academic Reading Practice hoàn thành' }).waitFor()
  await page.getByRole('tab',{ name:'Writing' }).click()
  await page.getByPlaceholder('Write your Task 1 response here…').fill(Array(155).fill('development').join(' '))
  await page.getByPlaceholder('Write your Task 2 response here…').fill(Array(255).fill('communication').join(' '))
  await page.getByRole('button',{ name:'Nộp Writing' }).click()
  await page.getByRole('heading',{ name:'Writing practice hoàn thành' }).waitFor()
  assert((await page.evaluate(() => JSON.parse(localStorage.getItem('nt_state_v1')).ieltsHistory?.length)) === 1, 'IELTS Writing result was not persisted')
  await page.getByRole('tab',{ name:'Speaking' }).click()
  await page.getByText('What do you like most about your home?').waitFor()
  console.log('PLATFORM checkpoint: IELTS 40-question Reading reaches result, Writing submits and Speaking opens')

  await page.goto(`${origin}/about`)
  await page.locator('footer').getByRole('link',{ name:'Đọc bài hành trình' }).click()
  await page.waitForURL('**/blog#nguyen-ngoc-tam-ninh-thuan')
  await page.locator('#nguyen-ngoc-tam-ninh-thuan').waitFor()
  await page.waitForFunction(() => { const node=document.getElementById('nguyen-ngoc-tam-ninh-thuan'); return node && Math.abs(node.getBoundingClientRect().top) < 220 })
  assert(true,'Footer blog hash link scrolled to the personal story')
  console.log('PLATFORM checkpoint: footer hash link scrolls to blog story')

  await page.setViewportSize({ width:1440,height:900 })
  await page.goto(`${origin}/`)
  const publicLearnBox = await page.getByRole('button',{ name:'Học', exact:true }).boundingBox()
  await page.goto(`${origin}/dashboard`)
  const appLearnBox = await page.getByRole('button',{ name:'Học', exact:true }).boundingBox()
  assert(publicLearnBox && appLearnBox && Math.abs(publicLearnBox.x-appLearnBox.x) < 1,'Header Học position shifted between public and app routes')
  assert(publicLearnBox && appLearnBox && Math.abs(publicLearnBox.width-appLearnBox.width) < 1,'Header Học width changed between routes')
  await page.getByRole('button',{ name:'Học', exact:true }).click()
  await page.getByRole('menuitem',{ name:'My Vocabulary' }).waitFor()
  await page.getByRole('button',{ name:'Học', exact:true }).click()
  assert(await page.locator('.desktop-nav').getByText('Dashboard',{ exact:true }).count() === 1,'Desktop nav is missing Dashboard')
  console.log('PLATFORM checkpoint: grouped desktop navigation opens without a long flat menu')

  await page.goto(`${origin}/contact`)
  const contactText=await page.locator('main.page').innerText()
  assert(!contactText.includes('VITE_CONTACT_EMAIL'),'Contact page leaked VITE_CONTACT_EMAIL')
  await page.getByRole('link',{ name:'GitHub' }).waitFor()
  await page.goto(`${origin}/privacy`)
  const privacyText=await page.locator('main.page').innerText()
  assert(!privacyText.includes('VITE_GA_ID'),'Privacy page leaked VITE_GA_ID')
  assert(privacyText.includes('Google Analytics'),'Privacy page is missing analytics status')
  console.log('PLATFORM checkpoint: contact and privacy hide deployment variable names')

  await page.goto(`${origin}/review`)
  await page.getByRole('heading',{ name:'Gợi ý hôm nay' }).waitFor()
  await page.getByRole('link',{ name:'Học từ mới' }).waitFor()
  assert((await page.evaluate(() => JSON.parse(localStorage.getItem('nt_state_v1')).todayMinutes)) < 15, 'Opening review inflated study time')

  await page.goto(`${origin}/my-vocabulary`)
  await page.getByLabel('Từ *').fill('waypoint')
  await page.getByLabel('Nghĩa tiếng Việt *').fill('điểm dừng trên đường')
  await page.getByLabel('Câu ví dụ',{ exact:true }).fill('The waypoint is near the station.')
  await page.getByLabel('Dịch câu ví dụ').fill('Điểm dừng ở gần nhà ga.')
  await page.getByRole('button',{ name:'Thêm vào kho từ' }).click()
  await page.getByText('waypoint',{ exact:true }).waitFor()
  await page.reload()
  await page.getByText('waypoint',{ exact:true }).waitFor()
  await page.getByLabel('Tên danh sách mới').fill('Từ du lịch')
  await page.getByRole('button',{ name:'Tạo danh sách' }).click()
  await page.getByLabel('Danh sách cho waypoint').selectOption({ label:'Từ du lịch' })
  await page.getByRole('button',{ name:/Từ du lịch \(1\)/ }).click()
  await page.getByText('waypoint',{ exact:true }).waitFor()
  await page.getByRole('button',{ name:'☆ Yêu thích' }).click()
  await page.getByRole('button',{ name:'Sửa' }).click()
  await page.getByLabel('Nghĩa tiếng Việt *').fill('điểm tham chiếu trên đường')
  await page.getByRole('button',{ name:'Lưu thay đổi' }).click()
  await page.reload()
  await page.getByText('điểm tham chiếu trên đường',{ exact:false }).waitFor()
  await page.goto(`${origin}/vocabulary?language=english&level=B1&word=waypoint`)
  await page.locator('.detailed-face.front h2').getByText('waypoint').waitFor()
  assert((await page.evaluate(() => JSON.parse(localStorage.getItem('nt_state_v1')).personalVocabulary?.length)) === 1, 'Personal word was not persisted')
  console.log('PLATFORM checkpoint: personal vocabulary, lists, edit, favorite and library integration')

  await page.goto(`${origin}/grammar?language=english&level=B1`)
  await page.getByRole('heading',{ name:'Present Perfect', exact:true }).waitFor()
  await page.locator('.grammar-practice .answer-list button').first().click()
  await page.getByRole('button',{ name:'Kiểm tra đáp án' }).click()
  await page.locator('.grammar-practice .feedback').waitFor()
  await page.getByRole('button',{ name:'☆ Lưu chủ điểm' }).click()
  await page.waitForFunction(() => (JSON.parse(localStorage.getItem('nt_state_v1')).savedItems || []).some((item) => item.type === 'Grammar'))
  await page.getByRole('link',{ name:/Mở phần ngữ pháp trong bài học/ }).click()
  await page.locator('.lesson-step-heading h1').getByText('Grammar').waitFor()
  assert((await page.locator('.lesson-head-progress > span').innerText()) === '0%', 'Jumping to Grammar incorrectly completed earlier sections')
  await page.locator('.lesson-grammar-quiz .answer-list button').filter({ hasText:'Present Perfect' }).click()
  await page.getByRole('button',{ name:'Kiểm tra ngữ pháp' }).click()
  await page.locator('.lesson-grammar-quiz .feedback.correct').waitFor()
  assert((await page.evaluate(() => Object.values(JSON.parse(localStorage.getItem('nt_state_v1')).lessonSessions || {}).some((session) => session.checked?.grammar && session.answers?.grammar !== null))), 'Lesson grammar answer was not persisted')
  await page.locator('.lesson-sidebar button').nth(7).click()
  await page.getByRole('button',{ name:'Hoàn thành bài học' }).click()
  await page.locator('.lesson-step-heading h1').getByText('Review').waitFor()
  await page.locator('.lesson-sidebar button').first().click()
  for (let section=0; section<7; section+=1) await page.getByRole('button',{ name:/Tiếp tục/ }).click()
  await page.getByRole('button',{ name:'Hoàn thành bài học' }).click()
  await page.getByText('LESSON COMPLETE!').waitFor()
  assert((await page.evaluate(() => JSON.parse(localStorage.getItem('nt_state_v1')).todayMinutes)) < 25, 'Lesson completion recorded the estimated duration rather than elapsed activity')
  await page.goto(`${origin}/grammar?language=chinese&level=HSK%206`)
  await page.getByRole('heading',{ name:'Lựa chọn với 与其…不如…' }).waitFor()
  assert((await page.evaluate(() => JSON.parse(localStorage.getItem('nt_state_v1')).savedItems || [])).some((item) => item.type === 'Grammar'), 'Grammar bookmark was not persisted')
  console.log('PLATFORM checkpoint: grammar library, quiz, bookmark and direct lesson section')

  await page.goto(`${origin}/my-vocabulary`)
  await page.getByRole('button',{ name:'Xóa', exact:true }).click()
  await page.getByRole('button',{ name:'Xác nhận xóa' }).click()
  assert((await page.evaluate(() => JSON.parse(localStorage.getItem('nt_state_v1')).personalVocabulary)).length === 0, 'Deleting a personal word did not persist')
  await page.goto(`${origin}/vocabulary?language=english&level=B1&word=adapt`)
  await page.locator('.vocabulary-list-picker button').first().click()
  await page.goto(`${origin}/my-vocabulary`)
  await page.getByRole('button',{ name:/Từ du lịch \(1\)/ }).click()
  await page.getByText('adapt',{ exact:true }).waitFor()
  await page.getByRole('button',{ name:/Xóa danh sách/ }).click()
  assert((await page.evaluate(() => JSON.parse(localStorage.getItem('nt_state_v1')).vocabularyLists)).length === 0, 'Deleting a vocabulary list did not persist')
  console.log('PLATFORM checkpoint: personal deletion and library-word lists')

  await page.goto(`${origin}/english/a1/lessons/english-a1-1-1?section=reading`)
  await page.getByRole('button',{ name:'Xem từ family' }).first().click()
  await page.getByRole('button',{ name:'Thêm vào My Vocabulary' }).click()
  assert((await page.evaluate(() => JSON.parse(localStorage.getItem('nt_state_v1')).personalVocabulary || [])).some((word) => word.word.toLowerCase() === 'family'), 'Reading vocabulary could not be added to My Vocabulary')
  await page.getByRole('button',{ name:'Đã thêm vào kho cá nhân' }).waitFor()
  console.log('PLATFORM checkpoint: reading vocabulary lookup and personal save')

  await page.goto(`${origin}/settings#profile`)
  await page.getByLabel('Tên hiển thị').fill('NT Learner')
  await page.getByLabel('Mục tiêu học').fill('IELTS 7.0')
  await page.getByRole('button',{ name:'Lưu hồ sơ' }).click()
  assert((await page.evaluate(() => JSON.parse(localStorage.getItem('nt_state_v1')).profile.displayName)) === 'NT Learner','Merged profile settings did not persist')

  await page.goto(`${origin}/ielts`)
  await page.getByLabel('Target band').selectOption('9')
  await page.reload()
  assert((await page.evaluate(() => JSON.parse(localStorage.getItem('nt_state_v1')).ieltsTarget)) === 9,'IELTS target 9 did not persist')

  await page.goto(`${origin}/english/b1`)
  await page.getByLabel('Hoạt động').selectOption('Vocabulary Lab')
  assert(await page.locator('.lesson-node').count() > 0,'Expanded course activity filter returned no lessons')
  await page.getByLabel('Hoạt động').selectOption('Listening & Speaking')
  assert(await page.locator('.lesson-node').count() > 0,'Listening & Speaking filter returned no lessons')

  await page.goto(`${origin}/english/b1/lessons/english-b1-1-1?section=listening`)
  await page.getByRole('progressbar',{ name:'Tiến độ audio' }).waitFor()
  console.log('PLATFORM checkpoint: merged profile, IELTS target, course filters and lesson audio')

  await page.goto(`${origin}/settings`)
  await page.getByLabel('Ngôn ngữ').selectOption('korean')
  await page.getByLabel('Level').selectOption('TOPIK 6')
  await page.getByRole('button',{ name:'20 từ' }).click()
  await page.reload()
  assert((await page.evaluate(() => JSON.parse(localStorage.getItem('nt_state_v1')).selectedLevel)) === 'TOPIK 6', 'Settings level selection was not persisted')
  assert((await page.evaluate(() => JSON.parse(localStorage.getItem('nt_state_v1')).dailyVocabularyGoal)) === 20, 'Daily vocabulary goal was not persisted')
  await page.goto(`${origin}/vocabulary?language=korean&level=TOPIK%206`)
  await page.locator('.vocabulary-index button').first().waitFor()
  assert(await page.locator('.vocabulary-index button').count() >= 5, 'High-level Korean vocabulary is unavailable')
  console.log('PLATFORM checkpoint: course and vocabulary-goal settings')

  for (const width of [320,375,768,1024,1440]) {
    await page.setViewportSize({ width,height:900 })
    for (const route of ['/vocabulary','/my-vocabulary','/grammar','/toeic','/ielts','/review']) {
      await page.goto(`${origin}${route}`)
      await page.locator('main.page').waitFor()
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth-document.documentElement.clientWidth)
      assert(overflow<=1,`${route} overflows at ${width}px by ${overflow}px`)
    }
  }
  assert(errors.length===0,`Runtime errors:\n${errors.join('\n')}`)
  await context.close()
  console.log('PLATFORM PASS: vocabulary, TOElish exams, IELTS, review, persistence and responsive layouts')
} finally {
  await browser?.close()
  server.kill('SIGTERM')
}

