import { ArrowRight, BarChart3, BookOpen, CalendarDays, Clock3, Flame, Layers3, RotateCcw, Sparkles, Star, Target, Type } from 'lucide-react'
import { Link } from 'react-router-dom'
import ProgressBar from '../components/common/ProgressBar'
import StatisticsCard from '../components/common/StatisticsCard'
import { useApp } from '../context/AppContext'
import { getRoadmap } from '../data/courses'
import { getLanguage } from '../data/languages'
import { allVocabulary, vocabularyForState } from '../services/vocabularyService'
import { getLevelProgress, summarizeProgress, totalStudyMinutes } from '../utils/progress'
import { isDue, localDate, wordKey } from '../utils/srs'
import { speak } from '../utils/speech'
import { languagePath, lessonPath, levelPath, vocabularyPath } from '../utils/routes'

export default function Dashboard() {
  const { state, setVocabularyMeta, setToast } = useApp()
  const language = getLanguage(state.selectedLanguage) || getLanguage('english')
  const level = language.levels.find(([name]) => name === state.selectedLevel)?.[0] || language.levels[0][0]
  const lessons = getRoadmap(language.id, level).flatMap((unit) => unit.lessons)
  const progress = getLevelProgress(state, language.id, level)
  const totals = summarizeProgress(state)
  const next = lessons.find((lesson) => !progress.completedLessons.includes(lesson.id)) || lessons[0]
  const percent = lessons.length ? Math.round((progress.completedLessons.filter((id) => lessons.some((lesson) => lesson.id === id)).length / lessons.length) * 100) : 0
  const vocabulary = vocabularyForState(state, language.id, level)
  const vocabularyDue = vocabulary.filter((word) => isDue(state.flashcardProgress[wordKey(word)])).length
  const vocabularyNew = vocabulary.filter((word) => !state.flashcardProgress[wordKey(word)] && !state.vocabularyMeta?.[wordKey(word)]?.started).length
  const vocabularyLearned = allVocabulary(state).filter((word) => state.flashcardProgress[wordKey(word)] || state.vocabularyMeta?.[wordKey(word)]?.learned).length
  const dayNumber = Math.floor(new Date().setHours(0, 0, 0, 0) / 86400000)
  const wordOfDay = vocabulary.length ? vocabulary[((dayNumber % vocabulary.length) + vocabulary.length) % vocabulary.length] : null
  const practicedToday = new Set((state.vocabularyActivity || []).filter((entry) => entry.date === localDate()).map((entry) => entry.key)).size
  const mistakeCounts = {
    grammar: state.mistakes.filter((item) => item.type === 'Grammar').length,
    listening: state.mistakes.filter((item) => item.type === 'Listening').length,
  }
  const skills = ['Listening', 'Speaking', 'Reading', 'Writing']
  const activity = [...Array(Math.max(0, 7 - state.activityHistory.length)).fill(0), ...state.activityHistory.slice(-7)]
  const weekdays = activity.map((_, index) => { const day = new Date(); day.setDate(day.getDate() - (6 - index)); return new Intl.DateTimeFormat('vi-VN', { weekday:'short' }).format(day) })
  const scores = Object.values(progress.lessonScores || {}).map(Number).filter(Number.isFinite)
  const accuracy = scores.length ? Math.round(scores.reduce((sum,value)=>sum+value,0)/scores.length) : 0
  const toeicScore = state.toeicHistory?.[0]?.score || '—'
  const ieltsBand = state.ieltsHistory?.[0]?.estimatedBand?.toFixed?.(1) || '—'
  return <div className="dashboard section-shell">
    <div className="dashboard-welcome"><div><span className="overline">CHÀO BẠN, {state.profile.displayName.split(' ').slice(-1)[0].toUpperCase()}</span><h1>Tiếp tục tạo nên tiến bộ <span>✦</span></h1></div><div className="date-chip"><CalendarDays /> Hôm nay · {new Intl.DateTimeFormat('vi-VN', { day: '2-digit', month: 'short' }).format(new Date())}</div></div>
    <section className="level-switcher" aria-labelledby="level-switch-title"><div><span className="overline">CURRENT LEVEL</span><h2 id="level-switch-title">{language.flag} {language.name} · {level}</h2><p>Đổi level bất kỳ lúc nào; tiến độ của mỗi level được giữ riêng.</p></div><div className="level-switch-links">{language.levels.map(([name]) => <Link className={name === level ? 'active' : ''} aria-current={name === level ? 'page' : undefined} key={name} to={levelPath(language.id,name)}>{name}</Link>)}</div><Link className="btn secondary" to={languagePath(language.id)}>Change Level</Link></section>
    <div className="dashboard-overview-stats"><StatisticsCard icon={Clock3} value={`${totalStudyMinutes(state, totals.studyMinutes)}m`} label="Total Study Time"/><StatisticsCard icon={Type} value={vocabularyLearned} label="Words Learned"/><StatisticsCard icon={BookOpen} value={totals.completedLessons} label="Lessons Completed"/><StatisticsCard icon={BarChart3} value={`${accuracy}%`} label="Accuracy"/><StatisticsCard icon={Target} value={toeicScore} label="TOEIC Score"/><StatisticsCard icon={Target} value={ieltsBand} label="IELTS Band"/></div>
    <section className="continue-card" style={{ '--accent': language.color }}><div className="continue-copy"><span className="continue-label"><Sparkles /> {percent === 100 ? 'LUYỆN TẬP LẠI' : 'TIẾP TỤC HỌC'}</span><div className="course-line"><span>{language.flag}</span><strong>{language.name} · {level}</strong></div><h2>Bài {next.number}: {next.title}</h2><p>{next.nativeTitle} · Từ vựng, ngữ pháp và luyện tập tổng hợp</p><div className="continue-meta"><span><Clock3 /> 20–40 phút</span><span><BookOpen /> 8 phần · 18 hoạt động</span></div><Link className="btn light large" to={lessonPath(language.id,level,next.id)}>{percent === 100 ? 'Practice Again' : progress.completedLessons.length ? 'Continue' : 'Start Learning'} <ArrowRight /></Link></div><div className="continue-art"><div className="art-circle">{next.icon}</div><span className="float-letter one">A</span><span className="float-letter two">✦</span><span className="float-letter three">Aa</span></div></section>
    {wordOfDay && <section className="panel word-of-day"><div><span className="overline">WORD OF THE DAY · {level}</span><h2>{wordOfDay.word} <small>{wordOfDay.ipa}</small></h2><p><strong>{wordOfDay.meaningVi}</strong>{wordOfDay.definition ? ` · ${wordOfDay.definition}` : ''}</p><p>{wordOfDay.example}</p><p>Từ đã luyện hôm nay: <strong>{practicedToday} / {state.dailyVocabularyGoal}</strong></p></div><div className="word-of-day-actions"><button className="btn secondary small" onClick={() => speak(wordOfDay.word, language.id, state.settings.speechSpeed === 'slow' ? .75 : state.settings.speechSpeed === 'fast' ? 1.25 : 1, setToast)}>Nghe phát âm</button><button className="btn secondary small" onClick={() => { setVocabularyMeta(wordOfDay, { started: true }); setToast(`Đã thêm “${wordOfDay.word}” vào danh sách đang học`) }}>Thêm vào từ đang học</button><Link className="text-link" to={vocabularyPath(language.id,level,wordOfDay.word)}>Xem thẻ →</Link></div></section>}
    <div className="dashboard-grid"><div className="dashboard-main"><section className="panel daily-goal"><div className="panel-title"><div><span className="panel-icon purple"><Clock3 /></span><div><h3>Daily Goal</h3><p>{state.dailyGoal} phút học hôm nay</p></div></div><Link to="/settings">Điều chỉnh</Link></div><div className="goal-row"><div className="goal-ring" style={{ '--p': `${Math.min(100, state.todayMinutes / state.dailyGoal * 100) * 3.6}deg` }}><span><strong>{state.todayMinutes}</strong><small>/{state.dailyGoal} phút</small></span></div><div className="goal-copy"><strong>{state.todayMinutes >= state.dailyGoal ? 'Đã hoàn thành mục tiêu!' : `Chỉ còn ${Math.max(0, state.dailyGoal - state.todayMinutes)} phút nữa`}</strong><p>Mục tiêu là tùy chọn và không khóa bất kỳ nội dung nào.</p><ProgressBar value={state.todayMinutes} max={state.dailyGoal} /></div></div></section>
      <section className="panel today-plan"><div className="panel-title"><div><span className="panel-icon purple"><CalendarDays /></span><div><h3>Gợi ý hôm nay</h3><p>Chọn hoạt động phù hợp, không cần làm theo thứ tự.</p></div></div></div><ul><li><span/><Link className="plan-link" to={vocabularyPath(language.id,level)}>Học từ mới ({vocabularyNew} từ)</Link></li>{vocabularyDue > 0 && <li><span/><Link className="plan-link" to={`${vocabularyPath(language.id,level)}?status=review`}>Ôn {vocabularyDue} từ đến hạn</Link></li>}<li><span/><Link className="plan-link" to={lessonPath(language.id,level,next.id)}>Tiếp tục bài {level}-{next.number}</Link></li>{state.mistakes.length > 0 && <li><span/><Link className="plan-link" to="/mistakes">Xem lại {state.mistakes.length} lỗi sai</Link></li>}<li><Sparkles/><Link className="plan-link" to="/self-study">Tự tạo bài luyện</Link></li></ul></section>
      <section className="panel"><div className="panel-title"><div><span className="panel-icon orange"><RotateCcw /></span><div><h3>Today&apos;s Review</h3><p>Dữ liệu từ lịch SRS và mistake notebook</p></div></div><Link to="/review">Xem tất cả</Link></div><div className="review-items"><div><span className="round-icon purple">Aa</span><strong>{vocabularyDue}</strong><small>từ cần ôn</small></div><div><span className="round-icon blue">⌘</span><strong>{mistakeCounts.grammar}</strong><small>lỗi ngữ pháp</small></div><div><span className="round-icon red">!</span><strong>{mistakeCounts.listening}</strong><small>bài nghe</small></div></div><div className="dashboard-review-sizes">{[5, 10, 20, 'all'].map((size) => <Link key={size} to={`/flashcards?language=${language.id}&level=${encodeURIComponent(level)}&limit=${size}`}>{size === 'all' ? 'Tất cả' : size}</Link>)}</div><Link to="/review" className="btn secondary full">Start Daily Review <ArrowRight /></Link></section>
      <section className="panel skill-quick"><div className="panel-title"><div><span className="panel-icon blue"><Layers3 /></span><div><h3>Skill Progress</h3><p>Điểm trung bình của level {level}</p></div></div><Link to="/progress">Chi tiết</Link></div>{skills.map((name) => <ProgressBar key={name} label={name} value={progress.skillScores[name] || 0} />)}</section></div>
      <aside className="dashboard-aside"><section className="panel stat-summary"><div><span className="big-icon flame"><Flame /></span><strong>{state.streak}</strong><small>day streak</small></div><div><span className="big-icon star"><Star /></span><strong>{state.xp.toLocaleString()}</strong><small>total XP</small></div></section><section className="panel current-course"><span className="overline">CURRENT COURSE</span><div className="current-course-top"><span className="flag small">{language.flag}</span><div><strong>{language.name}</strong><small>{level} · {language.framework}</small></div></div><ProgressBar value={percent} label="Course progress" /><div className="course-mini-stats"><span>{progress.completedLessons.length} bài hoàn thành</span><span>{vocabulary.filter((word) => state.flashcardProgress[wordKey(word)] || state.vocabularyMeta?.[wordKey(word)]?.learned).length} từ đã học</span><span>{progress.studyMinutes} phút học</span></div><Link to={levelPath(language.id,level)}>Xem lộ trình <ArrowRight /></Link></section><section className="panel weekly-mini"><div className="panel-title"><div><h3>Tuần này</h3><p>{activity.reduce((sum, value) => sum + Number(value || 0), 0)} phút học</p></div></div><div className="mini-bars">{activity.map((minutes, index) => <div key={index}><span style={{ height: `${Math.min(100, Math.max(5, Number(minutes || 0) * 5))}%` }} /><small>{weekdays[index]}</small></div>)}</div><Link className="text-link" to="/progress#history">Xem lịch sử học tập →</Link></section></aside></div>
  </div>
}

